export type { Channel, InboundMessage, OnInboundMessage, ChannelStatus } from './types.ts'
export { TelegramChannel } from './telegram.ts'
export type { TelegramChannelOpts } from './telegram.ts'
export { FeishuChannel } from './feishu.ts'
export type { FeishuChannelOpts } from './feishu.ts'
export { MessageRouter } from './router.ts'
export { ChannelManager } from './manager.ts'
export { CHANNEL_TYPE_REGISTRY, inferChannelType, validateChannelConfig, maskSecretFields } from './config-schema.ts'
export type { ChannelTypeInfo, ConfigFieldInfo } from './config-schema.ts'
export { createChannelFromRecord } from './factory.ts'
